# Generated by Django 6.1 on 2026-09-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_question_question_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
