# Generated by Django 6.1 on 2026-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_question_text_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
