# Generated by Django 6.1 on 2026-09-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_examattempt_user_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link_name', models.CharField(blank=True, help_text="URL name to reverse for the 'view' link, e.g. 'admin_student_scores'.", max_length=100)),
                ('link_arg', models.PositiveIntegerField(blank=True, help_text='Single positional arg for link_name, e.g. a user id.', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
