# Generated by Django 6.1 on 2026-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='retake_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='retake_requested',
            field=models.BooleanField(default=False),
        ),
    ]
