# Generated by Django 6.1 on 2026-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_retake_approved_profile_retake_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Wall-clock time from exam start to submission, in seconds.', null=True),
        ),
    ]
