# Generated by Django 6.1 on 2026-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_examattempt_time_taken_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='week',
            field=models.CharField(default='week1', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='week',
            field=models.CharField(choices=[('week1', 'Week 1'), ('week2', 'Week 2')], default='week1', max_length=10),
        ),
    ]
