from django.core.management.base import BaseCommand
from main.models import Question  # Adjust 'main' to match your Django app name

QUESTIONS_DATA = [
    {
        "pk": 1,
        "question": "A patient requests submission of an insurance claim for a crown that was never placed. The patient explains that annual benefits will expire soon and insists that 'everyone does it.' The patient suggests that reimbursement could be used toward future treatment instead. The receptionist refuses and informs the dentist of the request. The dentist explains that knowingly submitting inaccurate information to an insurance carrier is prohibited regardless of whether treatment may eventually occur. Submitting a claim for treatment that was not provided would be considered:",
        "option_a": "Coordination of benefits",
        "option_b": "Insurance fraud",
        "option_c": "Predetermination abuse",
        "option_d": "Professional discretion",
        "correct_option": "B",
    },
    {
        "pk": 2,
        "question": "A restorative practice has experienced increasing delays during afternoon appointments. The dentist routinely schedules crown preparations, endodontic procedures, and emergency examinations back-to-back. Although the morning schedule generally runs on time, delays accumulate throughout the afternoon, resulting in staff overtime and patient complaints. The office manager analyzes appointment flow and notices that procedures frequently exceed their estimated durations by 10–15 minutes. What scheduling modification would BEST reduce the impact of these delays?",
        "option_a": "Increase double booking of restorative procedures",
        "option_b": "Eliminate emergency appointments",
        "option_c": "Add strategically placed buffer time throughout the schedule",
        "option_d": "Shorten appointment lengths",
        "correct_option": "C",
    },
    {
        "pk": 3,
        "question": "A patient presents for treatment involving two Class II composite restorations. During check-in, the receptionist verifies insurance coverage and discovers that the patient recently changed employment and has not yet used any benefits under the new plan year. The plan includes an annual deductible of $75 and covers minor restorative procedures at 80%. The patient asks why payment is required when the procedure is supposedly '80% covered.' Which statement BEST describes the deductible?",
        "option_a": "The amount insurance will reimburse annually",
        "option_b": "The amount the patient pays before eligible benefits begin",
        "option_c": "The annual maximum payable by insurance",
        "option_d": "The percentage not covered by secondary insurance",
        "correct_option": "B",
    },
    {
        "pk": 4,
        "question": "A patient is referred to an oral surgeon for removal of an impacted mandibular third molar. During the consultation, the surgeon explains the relationship between the roots of the tooth and nearby anatomical structures visible on the panoramic radiograph. The assistant is asked to identify the structure most commonly associated with the inferior alveolar neurovascular bundle. Which anatomical structure houses the inferior alveolar nerve?",
        "option_a": "Mental foramen",
        "option_b": "Mandibular canal",
        "option_c": "Incisive canal",
        "option_d": "Infraorbital foramen",
        "correct_option": "B",
    },
    {
        "pk": 5,
        "question": "A 52-year-old patient presents for a comprehensive examination after not having seen a dentist for approximately six years. During the medical history review, the patient reports frequent headaches, jaw fatigue, and occasional discomfort when chewing tougher foods. The patient works long hours in a high-stress occupation and admits to clenching the teeth during the day. Clinical examination reveals moderate generalized attrition on posterior teeth and mild tenderness upon palpation of the muscles associated with mastication. The dentist asks the dental assistant to observe while evaluating muscle function. The patient is instructed to clench the teeth together while the dentist palpates the angle of the mandible. The dentist explains that the muscle being evaluated is one of the primary muscles responsible for elevating the mandible during chewing. Which muscle is being palpated at the angle of the mandible?",
        "option_a": "Buccinator",
        "option_b": "Masseter",
        "option_c": "Medial pterygoid",
        "option_d": "Temporalis",
        "correct_option": "B",
    },
    {
        "pk": 6,
        "question": "A dental office recently adopted electronic claim submission. Several claims are rejected immediately after transmission due to missing subscriber information and incorrect procedure codes. The receptionist is surprised because similar errors previously took weeks to identify when claims were mailed. What is the MAIN advantage of EDI claim submission?",
        "option_a": "Increased insurance reimbursement rates",
        "option_b": "Automatic approval of all claims",
        "option_c": "Faster identification and correction of claim errors",
        "option_d": "Elimination of coordination of benefits",
        "correct_option": "C",
    },
    {
        "pk": 7,
        "question": "A patient presents for placement of a Class II composite restoration on tooth 36. Following caries removal, the dentist determines that the preparation extends subgingivally on the proximal surface. The assistant prepares a matrix system to aid in contour development and restoration placement. Which matrix system is MOST appropriate?",
        "option_a": "Mylar strip",
        "option_b": "Tofflemire matrix",
        "option_c": "Orthodontic band",
        "option_d": "Bite registration tray",
        "correct_option": "B",
    },
    {
        "pk": 8,
        "question": "A patient contacts the office requesting copies of radiographs and chart records to transfer care to another city. The patient is scheduled to relocate within two weeks and asks that the information be forwarded immediately. The receptionist reviews office policy before responding. What must occur before records are released?",
        "option_a": "Obtain written patient authorization",
        "option_b": "Collect insurance payment first",
        "option_c": "Submit a predetermination",
        "option_d": "Contact the new dentist directly",
        "correct_option": "A",
    },
    {
        "pk": 9,
        "question": "A patient undergoing radiation therapy reports severe xerostomia and rapidly developing cervical carious lesions. The dentist explains the protective role of saliva. Which function of saliva MOST helps prevent dental caries?",
        "option_a": "Enhances plaque accumulation",
        "option_b": "Increases bacterial metabolism",
        "option_c": "Neutralizes acids and assists remineralization",
        "option_d": "Promotes calculus formation",
        "correct_option": "C",
    },
    {
        "pk": 10,
        "question": "A dental assistant employed at a busy clinic experiences significant financial difficulties. Over several months, the assistant intentionally alters patient payment records and diverts electronic refunds into a personal bank account. The discrepancy is eventually discovered during an external audit. Law enforcement becomes involved, and criminal charges are considered. The office manager explains to staff that some actions constitute violations against society rather than merely breaches of professional standards. Which area of law is MOST applicable in this scenario?",
        "option_a": "Common law",
        "option_b": "Contract law",
        "option_c": "Criminal law",
        "option_d": "Tort law",
        "correct_option": "C",
    },
    {
        "pk": 11,
        "question": "A busy dental practice with four operatories performs restorative, endodontic, and surgical procedures throughout the week. During a morning huddle, the dental assistant discovers that the office has only two boxes of anesthetic carpules remaining. The previous shipment was delayed due to severe weather conditions affecting transportation routes. The dentist recalls that several surgical extractions, crown preparations, and root canal treatments are scheduled during the next ten business days. The office manager reviews inventory records and notes that anesthetic carpules are typically consumed at a predictable rate each month. The office uses an inventory control system that identifies a predetermined stock level at which replacement supplies should be ordered before depletion occurs. What is the term used to describe the inventory level that triggers a new order?",
        "option_a": "Purchase quantity",
        "option_b": "Reorder point",
        "option_c": "Safety stock level",
        "option_d": "Back-order threshold",
        "correct_option": "B",
    },
    {
        "pk": 12,
        "question": "A dental office places an order for local anesthetic, fluoride varnish, prophy angles, and sterilization pouches through its primary supplier. Two days later, the supplier confirms shipment of most items but reports that the anesthetic carpules are temporarily unavailable because manufacturer production has not met demand. The office receives the remainder of the order and is informed that the missing anesthetic will be shipped once inventory becomes available. The receptionist asks the office manager how the missing item should be classified in the purchasing records. The unavailable anesthetic shipment is considered:",
        "option_a": "A reorder quantity",
        "option_b": "A safety stock reserve",
        "option_c": "A purchase discrepancy",
        "option_d": "A back order",
        "correct_option": "D",
    },
    {
        "pk": 13,
        "question": "A practice manager reviews inventory costs after noticing increased expenses associated with disposable supplies. The office frequently orders examination gloves, masks, and sterilization pouches in small quantities several times each month. The supplier offers discounted pricing for larger purchases but storage space in the sterilization area is limited. The manager must determine how much inventory should be ordered each time to balance storage limitations, ordering costs, and supply availability. Which term refers to the amount of a product ordered during each purchasing cycle?",
        "option_a": "Purchase quantity",
        "option_b": "Reorder point",
        "option_c": "Turnover rate",
        "option_d": "Carrying cost",
        "correct_option": "A",
    },
    {
        "pk": 14,
        "question": "A healthy 27-year-old patient presents for restoration of a deep carious lesion on tooth 46. Following review of the health history, the dentist administers an inferior alveolar nerve block. Several minutes later, the patient reports numbness involving the lower lip and chin on the right side. The dental assistant records the anesthetic details in the chart while the dentist tests the effectiveness of anesthesia before beginning treatment. The patient asks why the lip feels numb even though the treatment is being performed on a molar tooth. The dentist explains that a branch of the inferior alveolar nerve exits through an opening in the mandible and supplies sensation to the lower lip and chin. Through which anatomical structure does this nerve exit?",
        "option_a": "Mandibular foramen",
        "option_b": "Incisive canal",
        "option_c": "Mental foramen",
        "option_d": "Lingual foramen",
        "correct_option": "C",
    },
    {
        "pk": 15,
        "question": "A 42-year-old patient presents for crown preparation on tooth 36. During the financial consultation, the receptionist learns that the patient is covered under an employer-sponsored dental plan and is also listed under a spouse's dental insurance policy. The patient recently changed employment and asks which carrier should process claims first. The receptionist reviews coordination of benefits guidelines and determines that the patient's own employment plan remains active. Which plan is generally considered primary?",
        "option_a": "The spouse's plan with the higher annual maximum",
        "option_b": "The patient's own employer-sponsored plan",
        "option_c": "The plan submitted first electronically",
        "option_d": "The plan with the lower deductible",
        "correct_option": "B",
    },
    {
        "pk": 16,
        "question": "A 14-year-old patient presents for orthodontic consultation. The child's parents are divorced and both maintain dental insurance coverage. The child resides primarily with one parent throughout the year. The receptionist reviews insurance information before submitting a preauthorization request. Under typical coordination of benefits rules, which parent's plan is usually primary?",
        "option_a": "The parent with the highest annual maximum",
        "option_b": "The parent who submitted coverage first",
        "option_c": "The parent with custody and primary residence of the child",
        "option_d": "The parent with the lower deductible",
        "correct_option": "C",
    },
    {
        "pk": 17,
        "question": "A patient undergoes periodontal surgery and submits claims under both primary and secondary insurance plans. The primary carrier reimburses according to plan limitations. The secondary insurer receives the claim and explanation of benefits but reimburses only a portion of the remaining balance. The patient becomes upset and insists that 'double insurance' should eliminate all personal expenses. What is the PRIMARY purpose of coordination of benefits?",
        "option_a": "To guarantee full reimbursement of treatment fees",
        "option_b": "To ensure total reimbursement exceeds treatment costs",
        "option_c": "To coordinate payments while preventing overpayment",
        "option_d": "To eliminate deductibles from both plans",
        "correct_option": "C",
    },
    {
        "pk": 18,
        "question": "A busy restorative practice routinely experiences delays during afternoons. Procedures frequently run longer than expected because of anesthesia challenges, additional radiographs, patient questions, and unforeseen restorative complications. The office manager recommends reserving short periods throughout the schedule that are intentionally left unscheduled. Some staff members worry that these unused periods may reduce production. What is the PRIMARY purpose of buffer time?",
        "option_a": "To increase opportunities for double booking",
        "option_b": "To absorb scheduling delays and maintain workflow",
        "option_c": "To create additional staff break periods",
        "option_d": "To reduce chair utilization rates",
        "correct_option": "B",
    },
    {
        "pk": 19,
        "question": "A patient telephones at 9:15 a.m. complaining of severe spontaneous pain, facial swelling, and inability to sleep. The day's schedule includes multiple crown preparations, hygiene appointments, and a surgical extraction. The office maintains one emergency appointment slot each morning and another each afternoon. The morning emergency slot remains available. The receptionist discusses the situation with the dentist. What is the MOST appropriate scheduling decision?",
        "option_a": "Book the patient into the available emergency slot",
        "option_b": "Double-book the patient with a crown preparation",
        "option_c": "Schedule the patient at the next recall appointment",
        "option_d": "Delay treatment until a cancellation occurs",
        "correct_option": "A",
    },
    {
        "pk": 20,
        "question": "A dental assistant records that topical anesthetic was applied before administration of local anesthesia. At the end of the appointment, the assistant realizes the chart entry was incorrect because topical anesthetic was never used during the procedure. The patient has already left the office. The office uses electronic records with audit tracking capabilities. The assistant immediately reports the error to the dentist. What is the MOST appropriate action regarding the incorrect chart entry?",
        "option_a": "Delete the entry completely and recreate the chart note",
        "option_b": "Leave the record unchanged because treatment is complete",
        "option_c": "Ask another staff member to correct the entry anonymously",
        "option_d": "Correct the record according to office documentation protocols",
        "correct_option": "D",
    },
    {
        "pk": 21,
        "question": "A patient undergoing extensive restorative treatment discovers that an insurance estimate was significantly lower than the final amount reimbursed. The patient becomes upset and accuses the office of intentionally misleading him regarding costs. The receptionist calmly reviews the predetermination documents, treatment plan, insurance correspondence, and signed financial consent forms. Throughout the discussion, the receptionist remains respectful, avoids assigning blame, and provides accurate information regarding insurance limitations. The office manager later praises the receptionist for maintaining professional standards despite the challenging interaction. Which professional value is MOST demonstrated by providing truthful information while maintaining respectful patient communication?",
        "option_a": "Non-maleficence",
        "option_b": "Beneficence",
        "option_c": "Justice",
        "option_d": "Veracity",
        "correct_option": "D",
    },
    {
        "pk": 22,
        "question": "A 46-year-old patient presents for periodontal therapy. During treatment, the patient casually mentions that she is a well-known local politician currently undergoing treatment for a medical condition that has not yet been disclosed publicly. Several days later, the dental assistant attends a community fundraising event and is approached by an acquaintance who recognizes the assistant from the dental office. The acquaintance states that he recently saw the politician entering the dental clinic and asks whether she is ill because rumors have begun circulating online. The assistant knows that the individual has no involvement in the patient's care and is simply curious. The office has written privacy policies, annual confidentiality training, and secure electronic records. Which ethical principle is MOST applicable in this situation?",
        "option_a": "Justice",
        "option_b": "Veracity",
        "option_c": "Confidentiality",
        "option_d": "Beneficence",
        "correct_option": "C",
    },
    {
        "pk": 23,
        "question": "A growing dental practice performs hundreds of restorative and hygiene appointments monthly. To reduce administrative workload, the office enrolls in a supplier program that automatically ships selected products whenever inventory levels reach predetermined thresholds. The dental assistant notices that gloves, masks, fluoride varnish, and sterilization indicators arrive regularly without individual purchase orders being submitted. Which inventory system is MOST likely being used?",
        "option_a": "Just-in-time inventory system",
        "option_b": "Manual stock rotation system",
        "option_c": "Automatic shipment system",
        "option_d": "Emergency replenishment system",
        "correct_option": "C",
    },
    {
        "pk": 24,
        "question": "A patient presents for extraction of tooth 38. During the review of the medical history, the dental assistant notices documentation indicating a severe allergy to penicillin and a previous hospitalization following an allergic reaction. While preparing medications prescribed postoperatively, the assistant notices that the prescription written by the dentist includes a penicillin-based antibiotic. The patient is already seated and anesthetized when the discrepancy is identified. Which ethical principle MOST requires prevention of patient harm in this situation?",
        "option_a": "Justice",
        "option_b": "Fidelity",
        "option_c": "Non-maleficence",
        "option_d": "Autonomy",
        "correct_option": "C",
    },
    {
        "pk": 25,
        "question": "A patient undergoes extraction of an impacted third molar after signing all required consent documents. Several weeks later, the patient develops an unexpected complication despite treatment having been performed according to accepted standards of care. The patient files a civil lawsuit alleging damages resulting from the procedure. During discussions, a student dental assistant asks whether the case would be considered criminal or civil in nature. The dentist explains that disputes involving negligence and compensation are generally addressed through a particular branch of law. Under which area of law would this dispute MOST likely be addressed?",
        "option_a": "Criminal law",
        "option_b": "Constitutional law",
        "option_c": "Administrative law",
        "option_d": "Common law",
        "correct_option": "D",
    },
    {
        "pk": 26,
        "question": "An elderly patient presents for an examination after several years without dental care. Clinical findings include advanced periodontal disease, multiple carious lesions, and several fractured restorations. The patient reports living on a fixed income and expresses concern regarding treatment costs. The dentist carefully explains available treatment options, including alternatives that may be more financially manageable while still addressing urgent oral health needs. The dental assistant observes that the dentist spends considerable time ensuring the patient understands the advantages and disadvantages of each option. Which ethical principle is BEST demonstrated by acting in the patient's best interests?",
        "option_a": "Beneficence",
        "option_b": "Veracity",
        "option_c": "Confidentiality",
        "option_d": "Autonomy",
        "correct_option": "A",
    },
    {
        "pk": 27,
        "question": "A dentist schedules a crown preparation at 8:00 a.m. The patient requires local anesthesia, tooth preparation, gingival retraction, impressions, and fabrication of a provisional restoration. During the anesthetic onset period, the dentist moves to a second operatory to perform a limited emergency examination. A newly hired assistant asks why this scheduling technique is used. What is the PRIMARY objective of dove-tailing?",
        "option_a": "Increase inactive clinical time",
        "option_b": "Improve utilization of the dentist's working time",
        "option_c": "Eliminate the need for assistants",
        "option_d": "Prevent emergency appointments",
        "correct_option": "B",
    },
    {
        "pk": 28,
        "question": "A 63-year-old patient presents for a recall examination and prophylaxis appointment. The patient's medical history indicates controlled hypertension and hyperlipidemia. During the social history review, the patient reports smoking one package of cigarettes daily for over 35 years and consuming alcohol socially on weekends. Clinical examination reveals a thickened white patch on the lateral border of the tongue that cannot be removed with gauze. The patient reports that the area has been present for several months but has not caused pain or discomfort. No obvious signs of trauma are identified in the area. The dentist discusses risk factors for oral cancer and recommends further investigation. The white lesion described is MOST consistent with:",
        "option_a": "Candidiasis",
        "option_b": "Aphthous ulcer",
        "option_c": "Leukoplakia",
        "option_d": "Mucocele",
        "correct_option": "C",
    },
    {
        "pk": 29,
        "question": "A newly graduated dental assistant begins employment at a clinic where one of the dentists occasionally asks assistants to perform procedures that exceed the scope permitted by provincial regulations. One afternoon, the dentist asks the assistant to independently perform a procedure that legally requires direct dentist involvement. The office is running behind schedule, and several patients are waiting. The assistant feels uncomfortable but worries that refusing may create tension with the employer. What is the assistant's PRIMARY professional responsibility?",
        "option_a": "Follow the dentist's instructions regardless of regulations",
        "option_b": "Perform the procedure if the patient consents",
        "option_c": "Practice only within the legally authorized scope of practice",
        "option_d": "Delegate the procedure to another staff member",
        "correct_option": "C",
    },
    {
        "pk": 30,
        "question": "A newly hired receptionist attempts to improve office productivity by double-booking several short appointments during peak hours. Initially, production increases; however, patients begin waiting longer, assistants struggle with room turnover, and sterilization delays occur. The office manager reviews scheduling reports and determines that excessive double booking has reduced efficiency despite increasing chair occupancy. The manager proposes reducing double booking while increasing strategically placed buffer periods. Which scheduling approach is MOST likely to improve both efficiency and patient satisfaction?",
        "option_a": "Eliminate all emergency appointments and continue double booking",
        "option_b": "Increase double booking while reducing appointment lengths",
        "option_c": "Balance limited double booking with appropriate buffer time",
        "option_d": "Replace buffer time entirely with same-day treatment slots",
        "correct_option": "C",
    },
    {
        "pk": 31,
        "question": "A 41-year-old patient presents for a dental examination and expresses concern regarding soreness that develops repeatedly at the corners of the mouth. The patient recently completed a course of antibiotics and reports wearing complete dentures that are more than ten years old. Clinical examination reveals erythematous fissures at both commissures of the lips. The patient reports mild burning and discomfort when opening widely during meals. The dentist discusses possible contributing factors, including fungal infection, nutritional deficiencies, reduced vertical dimension, and chronic moisture accumulation. The patient asks what the condition is called. Which diagnosis is MOST appropriate?",
        "option_a": "Herpes labialis",
        "option_b": "Angular cheilitis",
        "option_c": "Traumatic fibroma",
        "option_d": "Lichen planus",
        "correct_option": "B",
    },
    {
        "pk": 32,
        "question": "A 58-year-old patient attends the office for replacement of several defective restorations. During the medical history review, the patient reports a 40-year history of tobacco use and occasional alcohol consumption. The patient denies pain but mentions noticing a red area on the floor of the mouth several months ago. Upon examination, the dentist observes a well-defined red lesion that appears velvety and cannot be wiped away. No signs of ulceration are present. The dentist explains that certain oral lesions carry a higher risk of malignant transformation than others and recommends referral for further evaluation. The patient is surprised because the lesion is completely asymptomatic. Which lesion is MOST strongly associated with a high risk of malignant transformation?",
        "option_a": "Fordyce granules",
        "option_b": "Erythroplakia",
        "option_c": "Geographic tongue",
        "option_d": "Linea alba",
        "correct_option": "B",
    },
    {
        "pk": 33,
        "question": "A patient presents for delivery of a crown on tooth 36. During the appointment, the dentist notices a minor porcelain defect that is unlikely to affect function but is visible under close inspection. The laboratory has already closed for the weekend, and the patient has traveled a considerable distance to attend the appointment. The dentist discusses the situation privately with the dental assistant and considers whether to proceed with cementation or schedule a replacement. The patient asks directly whether the restoration is exactly as originally prescribed. Which ethical principle requires honest disclosure to the patient?",
        "option_a": "Fidelity",
        "option_b": "Beneficence",
        "option_c": "Justice",
        "option_d": "Veracity",
        "correct_option": "D",
    },
    {
        "pk": 34,
        "question": "A patient covered under two insurance plans undergoes periodontal treatment. The primary insurance carrier processes the claim and pays according to plan limitations. The secondary carrier subsequently requests a copy of the Explanation of Benefits (EOB). Why is the EOB required?",
        "option_a": "To determine the remaining eligible balance",
        "option_b": "To calculate sterilization fees",
        "option_c": "To establish treatment necessity",
        "option_d": "To determine deductible amounts",
        "correct_option": "A",
    },
    {
        "pk": 35,
        "question": "A 16-year-old patient presents for a recall appointment accompanied by her mother. The patient completed orthodontic treatment six months ago and reports brushing twice daily. Clinical examination reveals several chalky white areas on the facial surfaces of the maxillary anterior teeth. The dentist reviews the patient's history and notes frequent consumption of sports drinks and sweetened beverages during athletic activities. Four bitewing radiographs are exposed and reveal no interproximal carious lesions. The mother asks whether the white areas are permanent and whether additional preventive measures should be considered. The dentist explains that the lesions are non-cavitated and discusses remineralization strategies. Which preventive agent is MOST effective for promoting remineralization of early enamel lesions?",
        "option_a": "Sodium fluoride varnish",
        "option_b": "Zinc oxide eugenol",
        "option_c": "Calcium hydroxide",
        "option_d": "Polycarboxylate cement",
        "correct_option": "A",
    },
]


class Command(BaseCommand):
    help = "Loads unique NDAEB assessment questions into the database"

    def handle(self, *args, **options):
        # Wipe old question entries to maintain clean primary keys
        Question.objects.all().delete()

        count = 0
        for item in QUESTIONS_DATA:
            Question.objects.create(
                id=item["pk"],
                question=item["question"],
                option_a=item["option_a"],
                option_b=item["option_b"],
                option_c=item["option_c"],
                option_d=item["option_d"],
                correct_option=item["correct_option"],
            )
            count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully loaded {count} unique questions into the database!"
            )
        )