from django.core.management.base import BaseCommand
from main.models import Question  # Adjust 'main' to match your Django app name

QUESTIONS_DATA = [
    {
        "pk": 1,
        "question": "A 52-year-old patient presents for a comprehensive examination after approximately six years without regular dental care. Her health history includes controlled hypertension, seasonal allergies, and occasional tension headaches. She works at a computer for most of the day and admits that she frequently clenches her teeth when concentrating. The intraoral examination shows generalized occlusal wear but no fractured restorations. During the extraoral examination, the dentist asks the patient to clench her posterior teeth firmly while palpating a thick muscle over the lateral surface of the mandibular ramus near the angle of the mandible. The muscle becomes distinctly prominent. Which muscle is the dentist most likely palpating?",
        "option_a": "Temporalis",
        "option_b": "Masseter",
        "option_c": "Medial pterygoid",
        "option_d": "Lateral pterygoid",
        "correct_option": "B",
    },
    {
        "pk": 2,
        "question": "A new patient recently moved to Canada after receiving dental treatment in several countries. During charting, the assistant notices that the previous dental record uses the ISO/FDI system rather than the Universal system. Tooth 36 is noted as having a large existing restoration. The patient also reports sensitivity in a different quadrant and is unsure whether a wisdom tooth was previously extracted. Before the dentist begins the examination, the assistant wants to correctly identify tooth 36. Which tooth is represented by 36 in the ISO/FDI system?",
        "option_a": "Mandibular right first molar",
        "option_b": "Mandibular left second premolar",
        "option_c": "Mandibular left first molar",
        "option_d": "Mandibular right second molar",
        "correct_option": "C",
    },
    {
        "pk": 3,
        "question": "A 47-year-old patient presents for a new-patient examination. He reports occasional bleeding during brushing but no spontaneous gingival pain. He smokes approximately five cigarettes daily, acknowledges irregular flossing, and says his father lost several teeth in his 50s. Clinical examination reveals generalized plaque and calculus. Most posterior probing depths are 3 to 4 mm; however, several sites around the maxillary molars measure 6 mm. Bleeding occurs at multiple sites. Radiographs reveal localized reduction in crestal bone height adjacent to the teeth with the deeper measurements. Which finding most clearly distinguishes the condition around those maxillary molars from uncomplicated gingivitis?",
        "option_a": "Bleeding during periodontal probing",
        "option_b": "Accumulation of subgingival calculus",
        "option_c": "Generalized plaque at the gingival margins",
        "option_d": "Deep periodontal pockets associated with supporting-bone loss",
        "correct_option": "D",
    },
    {
        "pk": 4,
        "question": "A 58-year-old patient taking several medications complains that her mouth has felt unusually dry for the past year. She brushes twice daily with fluoridated toothpaste and says she rarely eats candy, although she keeps mints at her desk. Several new cervical carious lesions are noted. As part of the assessment, the patient chews a paraffin pellet for 5 minutes and produces 2.5 mL of saliva. How should this stimulated salivary flow rate be interpreted according to the textbook?",
        "option_a": "Normal stimulated salivary flow",
        "option_b": "Low flow without reaching the dry-mouth level",
        "option_c": "Dry-mouth level associated with high caries risk",
        "option_d": "An uninterpretable result because collection exceeded 3 minutes",
        "correct_option": "C",
    },
    {
        "pk": 5,
        "question": "A returning patient is scheduled for preparation of a crown. His electronic chart shows controlled hypertension and no known allergies. The crown was planned three weeks earlier. While the assistant is placing the bib, the patient casually mentions that his physician started him on \"a new heart medication\" five days ago but says, \"It shouldn't matter because I feel fine.\" The anesthetic setup has already been prepared, and the dentist is finishing with another patient. What is the most appropriate next action by the dental assistant?",
        "option_a": "Continue preparing the patient and enter the medication after treatment",
        "option_b": "Ask only whether the new medication causes dry mouth before proceeding",
        "option_c": "Update the medical history and bring the medication change to the dentist's attention before treatment",
        "option_d": "Proceed because the written health history was updated when the crown was treatment-planned",
        "correct_option": "C",
    },
    {
        "pk": 6,
        "question": "A 44-year-old patient is scheduled for restorative treatment involving two mandibular molars. He has no significant medical conditions and previously tolerated local anesthetic without difficulty. During setup, a new assistant asks why the dentist commonly selects a nerve-block technique for mandibular posterior treatment rather than relying on the type of local infiltration frequently used for individual maxillary teeth. Which explanation best accounts for this difference?",
        "option_a": "The dense compact nature of mandibular bone limits diffusion of anesthetic solution",
        "option_b": "Mandibular teeth require anesthesia of a larger number of terminal nerve endings",
        "option_c": "The mandibular periodontal ligament prevents anesthetic from reaching the pulpal tissues",
        "option_d": "The inferior alveolar nerve lies too superficially for local infiltration to remain localized",
        "correct_option": "A",
    },
    {
        "pk": 7,
        "question": "During instrument processing, an assistant cleans and packages several reusable instruments. One group is placed inside a tightly closed solid metal container because the assistant wants to protect the instruments during the cycle. The chemical vapor sterilizer reaches the correct pressure and temperature and runs for the required time. The indicator on the outside of the container changes appropriately. What is the most important concern with this load?",
        "option_a": "The container may cause excessive condensation and corrosion of the instruments",
        "option_b": "The metal container may cause the sterilizer temperature to become too high",
        "option_c": "The chemical indicator cannot function accurately on a metal surface",
        "option_d": "The closed container may prevent the sterilizing agent from reaching the instruments",
        "correct_option": "D",
    },
    {
        "pk": 8,
        "question": "During a lengthy restorative procedure with a right-handed dentist, a student repeatedly passes instruments directly over the patient's face. The dentist stops the procedure and reminds the student that exchanges should occur within the designated area intended for instrument and material transfer. The patient is reclined, the dentist is seated in the usual operator position, and the assistant is seated opposite the dentist. Which clock position represents the transfer zone for a right-handed operator?",
        "option_a": "2 to 4 o'clock",
        "option_b": "4 to 7 o'clock",
        "option_c": "7 to 12 o'clock",
        "option_d": "12 to 2 o'clock",
        "correct_option": "B",
    },
    {
        "pk": 9,
        "question": "A 33-year-old patient presents with no current dental pain. The dentist is particularly concerned about recurrent decay between several posterior restorations and also wants to evaluate the height of the crestal bone between posterior teeth. The patient has a strong gag reflex and asks whether one panoramic image would provide everything required. Which intraoral image would most directly provide the information the dentist is seeking?",
        "option_a": "Posterior periapical image",
        "option_b": "Maxillary occlusal image",
        "option_c": "Bitewing image",
        "option_d": "Anterior periapical image",
        "correct_option": "C",
    },
    {
        "pk": 10,
        "question": "A patient is advised to have a tooth extracted. He asks whether root canal treatment could preserve it, how much healing time to expect, what complications could occur, and what might happen if he chooses no treatment. After discussing the options, he asks to take some time before deciding. Which combination most accurately represents the information required for meaningful informed consent according to the textbook?",
        "option_a": "Diagnosis, estimated fee, insurance coverage, and postoperative medication",
        "option_b": "Nature of treatment, benefits, significant risks, consequences of no treatment, and reasonable alternatives",
        "option_c": "Proposed treatment, dentist's preferred option, expected result, and patient's signature",
        "option_d": "Proposed treatment, anticipated pain, appointment duration, and written financial agreement",
        "correct_option": "B",
    },
    {
        "pk": 11,
        "question": "A patient reports altered sensation involving part of the face and several teeth following a previous injury. During review of head-and-neck anatomy, the assistant recalls that one cranial nerve provides much of the general sensory innervation to the face, teeth, oral cavity, and tongue and also has a motor component associated with mastication. Which cranial nerve best matches this description?",
        "option_a": "Trigeminal nerve",
        "option_b": "Facial nerve",
        "option_c": "Glossopharyngeal nerve",
        "option_d": "Hypoglossal nerve",
        "correct_option": "A",
    },
    {
        "pk": 12,
        "question": "During an anatomy review before assisting with maxillary anesthesia, the dentist asks the assistant to identify the nerve associated specifically with the mesiobuccal root of the maxillary first molar. The patient also has sinus congestion and a large restoration on the second premolar, but neither finding changes the anatomical question. Which nerve supplies the mesiobuccal root of the maxillary first molar according to the textbook?",
        "option_a": "Anterior superior alveolar nerve",
        "option_b": "Middle superior alveolar nerve",
        "option_c": "Posterior superior alveolar nerve",
        "option_d": "Greater palatine nerve",
        "correct_option": "B",
    },
    {
        "pk": 13,
        "question": "A 56-year-old patient reports clenching at night and says one mandibular molar \"feels slightly loose.\" The dentist notes wear facets and evidence of uneven occlusal forces. The tooth has mild mobility. Periodontal probing around that tooth is 2 to 3 mm, with no radiographic evidence of a periodontal pocket. There is localized bone change consistent with excessive occlusal forces. Which interpretation best fits these findings?",
        "option_a": "Occlusal trauma is sufficient by itself to establish periodontal pocket formation",
        "option_b": "Tooth mobility confirms periodontitis even if probing depths are normal",
        "option_c": "Occlusal trauma can contribute to mobility and bone changes without causing periodontal pocket formation",
        "option_d": "Any radiographic bone change accompanying mobility indicates a periodontal pocket",
        "correct_option": "C",
    },
    {
        "pk": 14,
        "question": "A patient completes a restorative appointment that included local anesthesia, placement of a liner, a posterior restoration, occlusal adjustment, and postoperative instructions. The patient also asks the receptionist to send an updated insurance estimate and changes the telephone number on file. At the end of the day, the assistant realizes that the clinical entry contains only: \"Filling completed. Patient fine.\" Which addition would most strengthen the clinical record?",
        "option_a": "Detailed treatment provided, relevant materials, instructions, and other clinically important events from the appointment",
        "option_b": "The patient's complete account balance, insurance estimate, and payment arrangement",
        "option_c": "Only the diagnosis and planned date of the patient's next recall appointment",
        "option_d": "Only the tooth number and dentist's initials because other details are stored elsewhere",
        "correct_option": "A",
    },
    {
        "pk": 15,
        "question": "A cooperative 12-year-old patient has newly erupted permanent molars with deep occlusal fissures. The tooth is cleaned, etched, rinsed, and dried. Just before the sealant is placed, the patient turns to answer a question and saliva briefly contacts the etched surface. The surface is dried again and appears chalky. What is the most significant concern if the procedure simply continues without addressing the contamination?",
        "option_a": "The sealant will polymerize too quickly and create an occlusal interference",
        "option_b": "Moisture contamination may compromise sealant adhesion and increase the risk of partial or complete failure",
        "option_c": "The etched enamel will become too porous and retain excessive sealant",
        "option_d": "Saliva will permanently prevent the enamel from undergoing remineralization",
        "correct_option": "B",
    },
    {
        "pk": 16,
        "question": "A former patient requests transfer of information to a new dental office. During preparation of the records, a new employee suggests deleting several old progress notes because the treatment has been completed and the patient no longer attends the practice. Another employee proposes keeping only recent radiographs. Which description best explains why this approach is inappropriate?",
        "option_a": "The dental record is a permanent legal document that may have evidentiary and other reference uses",
        "option_b": "Only the financial portion of the record must be maintained permanently",
        "option_c": "Once treatment is completed, only radiographs retain legal significance",
        "option_d": "The record becomes the property of the new dentist when the patient transfers",
        "correct_option": "A",
    },
    {
        "pk": 17,
        "question": "A competent adult patient has extensive periodontal findings but refuses recommended radiographs because of concerns about radiation. The dentist explains why the images are considered necessary to properly assess the condition. The patient responds, \"I'll sign whatever waiver you want, but just treat me without them.\" According to the principles described in the textbook, what is the most accurate interpretation?",
        "option_a": "A signed refusal transfers responsibility for diagnostic limitations entirely to the patient",
        "option_b": "The dentist must provide treatment because the patient's autonomy overrides the standard of care",
        "option_c": "Informed refusal should be documented, but it does not permit the dentist to provide care considered substandard",
        "option_d": "Once the patient signs a waiver, further discussion of the consequences is unnecessary",
        "correct_option": "C",
    },
    {
        "pk": 18,
        "question": "A general dentist identifies a lesion that requires evaluation by a specialist. The patient is anxious, asks whether the referral means cancer is suspected, and initially says she would rather wait several months. The dentist explains the reason for referral and provides the name of an appropriate specialist. Which chart entry would provide the most complete referral documentation?",
        "option_a": "\"Referral recommended; patient advised.\"",
        "option_b": "\"Patient anxious; specialist information given.\"",
        "option_c": "\"Lesion noted; referral letter sent to specialist.\"",
        "option_d": "Description of the problem, reason for referral, specialist's name and specialty, and whether the patient agreed to the referral",
        "correct_option": "D",
    },
    {
        "pk": 19,
        "question": "During administration of an inferior alveolar nerve block, the patient is calm and reports no discomfort. Before depositing solution, the dentist retracts the thumb ring. A thin line of blood enters the anesthetic cartridge. The patient has a normal pulse and is not experiencing dizziness. What should occur next?",
        "option_a": "Inject slowly because only a small amount of blood entered the cartridge",
        "option_b": "Reposition the needle before depositing the anesthetic solution",
        "option_c": "Remove the cartridge and replace it while leaving the needle in the same position",
        "option_d": "Inject a smaller quantity and aspirate again only after half the cartridge has been delivered",
        "correct_option": "B",
    },
    {
        "pk": 20,
        "question": "Following a local anesthetic injection, the dentist intends to use the same syringe again later during the procedure. The needle must therefore be recapped temporarily. The assistant is wearing appropriate PPE and has a sharps container nearby. Which technique is most consistent with the textbook's work-practice controls?",
        "option_a": "Recap using a one-handed scoop technique or an approved capping device",
        "option_b": "Stabilize the cap with one hand while directing the needle into it with the other",
        "option_c": "Hold the syringe while the dentist replaces the cap using both hands",
        "option_d": "Remove the needle from the syringe before recapping it on the tray",
        "correct_option": "A",
    },
    {
        "pk": 21,
        "question": "A dental assisting student assembles an aspirating syringe correctly except that the harpoon does not engage the rubber stopper of the cartridge. The cartridge is undamaged, the needle is securely attached, and anesthetic can still be expelled when the plunger is advanced. Which important function is primarily compromised by failure of the harpoon to engage?",
        "option_a": "Identifying the anesthetic solution through the cartridge window",
        "option_b": "Preventing anesthetic from leaking through the threaded tip",
        "option_c": "Retracting the stopper to create the negative pressure needed for aspiration",
        "option_d": "Controlling the rate at which anesthetic exits through the needle lumen",
        "correct_option": "C",
    },
    {
        "pk": 22,
        "question": "A patient is receiving a Class III composite restoration. Local anesthesia and isolation have been completed. The preparation has been finished, the tooth has been etched, rinsed, and dried, the matrix strip is in place, and primer has been applied. The assistant is organizing the remaining materials while the dentist maintains the isolated field. Which material should be prepared next before insertion of the composite restorative material?",
        "option_a": "Finishing and polishing material",
        "option_b": "Bonding resin",
        "option_c": "Articulating medium",
        "option_d": "Cavity varnish",
        "correct_option": "B",
    },
    {
        "pk": 23,
        "question": "During a Class II posterior restoration, the matrix band appears secure around the tooth. The dentist notices, however, that the band is not closely adapted at the gingival margin of the proximal preparation. The assistant has several different wedges ready, and the contact area is relatively tight. What is the primary reason for placing the appropriately sized wedge in this situation?",
        "option_a": "To increase the occlusal height of the matrix band",
        "option_b": "To prevent the matrix retainer from rotating toward the tongue",
        "option_c": "To adapt the matrix firmly at the gingival margin and help establish proper proximal contour",
        "option_d": "To prevent restorative material from bonding to the occlusal surface",
        "correct_option": "C",
    },
    {
        "pk": 24,
        "question": "Immediately after a posterior restoration is finished, the patient reports that the tooth feels \"a little tall.\" The patient was asymptomatic before treatment and the local anesthetic is still partially effective. The dentist places articulating paper and asks the patient to tap gently and then move the mandible from side to side. Several marks appear, but one area shows particularly heavy blue markings on the new restoration. What do the heavy marks most likely indicate?",
        "option_a": "An inadequately cured area of the restoration",
        "option_b": "An open proximal contact",
        "option_c": "Incomplete removal of the smear layer",
        "option_d": "A high occlusal contact requiring adjustment",
        "correct_option": "D",
    },
    {
        "pk": 25,
        "question": "A patient undergoing root canal treatment has already had an initial diagnostic periapical image. Local anesthesia and dental-dam isolation are completed, access has been made, and a file with a rubber stop is positioned in the canal. Before continuing enlargement of the canal, the dentist asks for another periapical image. Which radiographic image is being requested?",
        "option_a": "Initial diagnostic image",
        "option_b": "Working-length image",
        "option_c": "Final-instrumentation image",
        "option_d": "Root-canal-completion image",
        "correct_option": "B",
    },
    {
        "pk": 26,
        "question": "Near the end of root canal therapy, the canals have been cleaned, shaped, irrigated, and dried. The assistant prepares paper points, gutta-percha points, sealer, and several endodontic instruments. The patient asks what material will actually remain in the canal when treatment is completed. Which combination most directly performs the canal-obturation function described in the textbook?",
        "option_a": "Sodium hypochlorite and paper points",
        "option_b": "Calcium hydroxide and EDTA",
        "option_c": "Gutta-percha points and root canal sealer",
        "option_d": "Chlorhexidine and temporary restorative material",
        "correct_option": "C",
    },
    {
        "pk": 27,
        "question": "A healthy adult has an uncomplicated extraction of a mandibular premolar. The patient is given written postoperative instructions, but before leaving asks whether the gauze should be removed as soon as the anesthetic begins to wear off. Bleeding is controlled and no unusual complication occurred. Which instruction most closely follows the textbook?",
        "option_a": "Remove the pressure pack after approximately 10 minutes",
        "option_b": "Keep the pressure pack in place for approximately 30 to 45 minutes",
        "option_c": "Keep the pressure pack continuously in place for 2 to 3 hours",
        "option_d": "Remove the pack once saliva no longer appears pink, regardless of time",
        "correct_option": "B",
    },
    {
        "pk": 28,
        "question": "A 29-year-old patient telephones three days after removal of a mandibular molar. She says the first day was uncomfortable but manageable; the pain then became much more intense and now seems to radiate toward the side of her face. She smoked several cigarettes the evening after surgery and admits she used a straw because she was \"trying not to chew.\" She does not report facial swelling or fever. Which postoperative complication best fits this presentation?",
        "option_a": "Acute pulpitis",
        "option_b": "Postoperative paresthesia",
        "option_c": "Hematoma formation",
        "option_d": "Alveolar osteitis",
        "correct_option": "D",
    },
    {
        "pk": 29,
        "question": "A teenager begins fixed orthodontic treatment. At the first band-fitting appointment, the orthodontic assistant finds that the mesial and distal contacts of a first molar are too tight to allow the band to seat properly. The tooth is fully erupted and there is no active decay. Which step is most appropriate before attempting to fit the band at a later visit?",
        "option_a": "Place a separator to create slight interproximal space",
        "option_b": "Bond a bracket to the molar before seating the band",
        "option_c": "Reduce the proximal enamel until the band passes the contacts",
        "option_d": "Cement the band partially and allow occlusal pressure to seat it",
        "correct_option": "A",
    },
    {
        "pk": 30,
        "question": "A heat-sensitive reusable item has been cleaned and immersed completely in a glutaraldehyde solution. The assistant removes it after 45 minutes because the schedule is busy and says, \"It has been in a sterilizing chemical, so it is sterile.\" According to the textbook, how should the processing level be classified?",
        "option_a": "Sterilized because the item was completely immersed",
        "option_b": "Sterilized because glutaraldehyde is a liquid chemical sterilant",
        "option_c": "Disinfected rather than sterilized because the required sterilization contact time was not met",
        "option_d": "Unprocessed because liquid chemicals cannot disinfect dental items",
        "correct_option": "C",
    },
    {
        "pk": 31,
        "question": "Two heat-tolerant metal items need processing. One is inside a closed metal container. An assistant is comparing chemical-vapor sterilization with static dry-heat sterilization and remembers that the packaging requirements differ. Which method described in the textbook can accommodate metal or glass containers in circumstances where a closed container would be inappropriate for chemical-vapor sterilization?",
        "option_a": "Static dry-heat sterilization",
        "option_b": "Chemical-vapor sterilization",
        "option_c": "Liquid glutaraldehyde sterilization",
        "option_d": "Ethylene oxide only",
        "correct_option": "A",
    },
    {
        "pk": 32,
        "question": "A patient who uses a wheelchair can bear weight briefly and usually transfers with assistance. The treatment room has been cleared, and the wheelchair has been positioned close to the dental chair at approximately a 45-degree angle. The assistant is preparing to apply a gait belt and help the patient stand. What should be done before beginning the standing transfer?",
        "option_a": "Recline the dental chair fully and remove the wheelchair armrest",
        "option_b": "Lock the wheelchair and raise the footrests",
        "option_c": "Have the patient place both feet on the wheelchair footrests for leverage",
        "option_d": "Move the wheelchair farther away to provide turning space",
        "correct_option": "B",
    },
    {
        "pk": 33,
        "question": "A patient with diabetes arrives for a long morning appointment. He took his usual insulin but was rushing and did not eat breakfast. About 30 minutes into treatment, he becomes shaky, sweaty, confused, and increasingly difficult to follow during conversation. The patient had been anxious before treatment, but the change is abrupt. Which condition is most consistent with this presentation?",
        "option_a": "Hyperglycemia",
        "option_b": "Vasovagal syncope",
        "option_c": "Hypoglycemia",
        "option_d": "Hyperventilation",
        "correct_option": "C",
    },
    {
        "pk": 34,
        "question": "A returning patient arrives for a routine recall appointment and says, \"Nothing has changed medically since last time.\" His most recent written medical-dental health history is already in the electronic record. He appears healthy and has no current complaint. According to the textbook, what should happen to the health history at this appointment?",
        "option_a": "No review is required unless the patient reports a change",
        "option_b": "It should be updated only before surgical or restorative treatment",
        "option_c": "It should be reviewed only once each calendar year",
        "option_d": "The returning patient should be asked to update it at every appointment",
        "correct_option": "D",
    },
    {
        "pk": 35,
        "question": "During a restorative procedure, the dentist asks for a hand instrument designed to reach an interproximal area. A student selects an instrument primarily because it has a wide padded handle. The dentist explains that although handle design affects grasp and comfort, another part of the instrument is especially important for access to different tooth surfaces. Which design feature is most directly responsible for enabling the working end to reach an interproximal area?",
        "option_a": "Increased circumference of the handle",
        "option_b": "Additional bends or angles in the shank",
        "option_c": "A serrated rather than smooth nib",
        "option_d": "Greater thickness of the working end",
        "correct_option": "B",
    },
    {
        "pk": 36,
        "question": "A patient has posterior bitewings exposed to evaluate suspected interproximal caries. The receptor placement appears acceptable, and the images have adequate density and contrast. However, the proximal contacts are overlapped, making the interproximal surfaces difficult to evaluate. The patient remained completely still during exposure. Which technical error most likely caused this problem?",
        "option_a": "Excessive vertical angulation",
        "option_b": "Insufficient vertical angulation",
        "option_c": "Incorrect horizontal angulation",
        "option_d": "Incorrect receptor exposure time",
        "correct_option": "C",
    },
    {
        "pk": 37,
        "question": "A periapical image is exposed using the bisecting-angle technique. The tooth and surrounding structures are visible, but the tooth appears noticeably shorter on the image than it does anatomically. The receptor was not bent, and the patient did not move. Which error most likely produced this appearance?",
        "option_a": "Excessive vertical angulation",
        "option_b": "Insufficient vertical angulation",
        "option_c": "Excessive horizontal angulation",
        "option_d": "Insufficient horizontal angulation",
        "correct_option": "A",
    },
    {
        "pk": 38,
        "question": "A 9-year-old patient has a recently erupted permanent first molar. The tooth is fully erupted, has deep pits and fissures, and no obvious occlusal caries. Bitewing examination shows no proximal lesion. The child is cooperative and isolation can be maintained. An adjacent molar has already required an occlusal restoration. Which treatment consideration is most consistent with the textbook?",
        "option_a": "The tooth is a strong candidate for pit-and-fissure sealant placement",
        "option_b": "Sealant is contraindicated because an adjacent tooth has been restored",
        "option_c": "Sealant should be delayed until the fissures show early cavitation",
        "option_d": "Sealant is contraindicated because only primary molars should be sealed at this age",
        "correct_option": "A",
    },
    {
        "pk": 39,
        "question": "Two sealants are being discussed for posterior teeth. One product is filled and the other is unfilled. The assistant recalls that both can penetrate fissures effectively and can have similar retention, but there is a practical difference after placement. Which statement best describes that difference according to the textbook?",
        "option_a": "Filled sealants cannot be light cured, whereas unfilled sealants can",
        "option_b": "Filled sealants may require checking and adjustment of the occlusion because they resist wear",
        "option_c": "Unfilled sealants require more occlusal adjustment because they are harder than filled materials",
        "option_d": "Unfilled sealants cannot be used on newly erupted permanent molars",
        "correct_option": "B",
    },
    {
        "pk": 40,
        "question": "During a comprehensive periodontal assessment, a student records only the deepest probing measurement found around each tooth. The dentist explains that this is not sufficient even when the gingiva appears generally healthy and the radiographs show little bone loss. How many periodontal probing-depth measurements does the textbook describe recording for each tooth?",
        "option_a": "Two",
        "option_b": "Four",
        "option_c": "Six",
        "option_d": "Eight",
        "correct_option": "C",
    },
    {
        "pk": 41,
        "question": "A multirooted mandibular molar has periodontal attachment loss. The clinician wants to determine whether disease has extended into the area between the roots and assess the dimensions of that involvement. A standard periodontal probe is already on the tray. Which instrument is specifically designed for this additional assessment?",
        "option_a": "Williams periodontal probe",
        "option_b": "Furcation probe",
        "option_c": "Explorer",
        "option_d": "Periodontal file",
        "correct_option": "B",
    },
    {
        "pk": 42,
        "question": "A patient receives an inferior alveolar nerve block before treatment on a mandibular first molar. The teeth, lower lip, and tongue become numb as expected, but the patient continues to feel manipulation of the buccal soft tissue adjacent to the molar. The dentist wants additional anesthesia specifically for that tissue. Which injection is most appropriate based on the anatomical distribution described in the textbook?",
        "option_a": "Incisive nerve block",
        "option_b": "Buccal nerve block",
        "option_c": "Mental nerve block",
        "option_d": "Lingual nerve block",
        "correct_option": "B",
    },
    {
        "pk": 43,
        "question": "Three adjacent maxillary teeth are scheduled for restorative treatment. The dentist wants anesthesia over a larger terminal nerve branch supplying a broader operative area rather than depositing solution only at the nerve endings of a single tooth. The procedure does not involve an entire quadrant. Which injection approach most closely matches this description?",
        "option_a": "Local infiltration",
        "option_b": "Field block",
        "option_c": "Main nerve-trunk block",
        "option_d": "Periodontal ligament injection",
        "correct_option": "B",
    },
    {
        "pk": 44,
        "question": "A 61-year-old patient has type 2 diabetes, smokes, and reports nighttime bruxism. Examination shows plaque, calculus, generalized bleeding on probing, several 6-mm periodontal pockets, and mobility of one molar. Vertical bitewings show interproximal crestal bone loss. The patient believes the entire problem is caused by grinding because his brother also grinds his teeth. Which finding provides the strongest evidence that supporting periodontal tissues have been destroyed rather than this being gingival inflammation or occlusal trauma alone?",
        "option_a": "Presence of generalized bleeding on probing",
        "option_b": "History of nighttime bruxism",
        "option_c": "Six-millimetre pockets together with radiographic bone loss",
        "option_d": "Presence of calculus on several posterior teeth",
        "correct_option": "C",
    },
    {
        "pk": 45,
        "question": "During root canal treatment on a multirooted tooth, the canals have already been enlarged to their planned sizes. Before obturation, the dentist places the final-size files in all canals and asks the assistant to expose a periapical image. Which image is being obtained?",
        "option_a": "Working-length image",
        "option_b": "Final-instrumentation image",
        "option_c": "Root-canal-completion image",
        "option_d": "Recall image",
        "correct_option": "B",
    },
    {
        "pk": 46,
        "question": "A patient requires restoration of a proximal lesion on an anterior tooth. The preparation extends through the proximal surface, and a tooth-coloured restorative material will be used. The dentist wants a matrix that can help reproduce the contour while permitting curing light to pass through the material. Which matrix is most appropriate?",
        "option_a": "Universal stainless-steel matrix band with retainer",
        "option_b": "Sectional posterior matrix with tension ring",
        "option_c": "Clear plastic/Mylar matrix strip",
        "option_d": "Copper band matrix",
        "correct_option": "C",
    },
    {
        "pk": 47,
        "question": "A patient declines recommended diagnostic radiographs but agrees to sign a form stating that she accepts \"all responsibility for anything the dentist cannot see.\" She then asks the dentist to proceed with extensive restorative treatment. The dentist believes that treating without the needed diagnostic information would compromise the standard of care. What is the most appropriate interpretation according to the textbook?",
        "option_a": "The signed waiver permits treatment because financial and diagnostic risks now belong to the patient",
        "option_b": "The patient's refusal must be respected, but the dentist is not required to provide care considered substandard",
        "option_c": "The dentist must perform only the treatment the patient personally requests",
        "option_d": "Treatment may proceed as long as the assistant witnesses the patient's signature",
        "correct_option": "B",
    },
    {
        "pk": 48,
        "question": "During root canal therapy, the dentist asks the assistant for a solution that has antimicrobial action and can help dissolve necrotic pulpal tissue and organic debris. Several materials are already on the endodontic tray, including EDTA, chlorhexidine, sodium hypochlorite, and gutta-percha. Which material best fits the dentist's request as described in the textbook?",
        "option_a": "EDTA",
        "option_b": "Chlorhexidine",
        "option_c": "Sodium hypochlorite",
        "option_d": "Gutta-percha",
        "correct_option": "C",
    },
    {
        "pk": 49,
        "question": "An orthodontic patient returns after brackets have been bonded on several teeth. A molar band still cannot be seated because the proximal contacts are too tight. There is no defective restoration or caries preventing seating, and the band size appears appropriate. Which action best addresses the problem before the band is fitted?",
        "option_a": "Place an orthodontic separator and allow slight tooth movement",
        "option_b": "Select a wider band and force it through the contact",
        "option_c": "Bond the arch wire directly to the molar without an attachment",
        "option_d": "Reduce the gingival edge of the band until it bypasses the contact",
        "correct_option": "A",
    },
    {
        "pk": 50,
        "question": "A patient requests an elective procedure because she believes it will produce a more attractive smile. After examination, the dentist believes the requested treatment would unnecessarily damage otherwise healthy tooth structure and recommends a less invasive alternative. The patient understands the explanation but insists, \"They're my teeth, so if I consent, you should do exactly what I'm asking.\" Which ethical principle most directly explains why patient choice alone does not obligate the dentist to provide a treatment believed to cause unnecessary harm?",
        "option_a": "Autonomy",
        "option_b": "Justice",
        "option_c": "Veracity",
        "option_d": "Nonmaleficence",
        "correct_option": "D",
    },
]


class Command(BaseCommand):
    help = "Loads unique NDAEB assessment questions into the database"

    def handle(self, *args, **options):
        # Wipe old question entries to maintain clean primary keys
        Question.objects.all().delete()

        count = 0
        for item in QUESTIONS_DATA:
            Question.objects.create(
                id=item["pk"],
                question=item["question"],
                option_a=item["option_a"],
                option_b=item["option_b"],
                option_c=item["option_c"],
                option_d=item["option_d"],
                correct_option=item["correct_option"],
            )
            count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully loaded {count} unique questions into the database!"
            )
        )