from django.core.management.base import BaseCommand
from main.models import Question  # Adjust 'main' to match your Django app name


QUESTIONS_DATA = [
    {
        "pk": 1,
        "question": "A 19-year-old patient presents for a recall examination after beginning university eight months ago. She reports drinking flavoured coffee throughout the morning and occasionally sipping sports drinks during late-night study sessions. She brushes twice daily and has no restorations. The dentist identifies a chalky white area on the smooth facial surface of a maxillary premolar. The enamel surface remains intact, and no cavitation is detected clinically. The patient asks whether the area must immediately be restored. Which description best explains the biological process occurring at this stage?",
        "option_a": "The lesion represents irreversible destruction of enamel because any visible white lesion is cavitated",
        "option_b": "The lesion represents an incipient stage in which demineralization may alternate with remineralization without loss of tooth structure",
        "option_c": "The lesion represents recurrent caries occurring beneath intact enamel",
        "option_d": "The lesion represents root caries progressing beneath the cementoenamel junction",
        "correct_option": "B",
    },
    {
        "pk": 2,
        "question": "A 72-year-old patient has maintained most of his natural teeth. He takes an antihypertensive medication and an antihistamine daily and complains that his mouth often feels dry. Examination reveals gingival recession on several mandibular teeth and a soft carious lesion near the cervical area of one premolar. His coronal enamel elsewhere appears relatively intact. Which factor most specifically explains why the exposed surface is particularly susceptible to caries?",
        "option_a": "Cementum contains less mineral and is more soluble than enamel",
        "option_b": "Recession increases the thickness of the acquired pellicle",
        "option_c": "Root surfaces receive less fluoride because they are located below the occlusal plane",
        "option_d": "Cementum is more highly mineralized and therefore traps cariogenic bacteria more effectively",
        "correct_option": "A",
    },
    {
        "pk": 3,
        "question": "A first-time mother asks why the dental team is discussing her own caries activity during her infant's preventive appointment. The baby has no erupted teeth yet. The mother reports that she frequently tastes food from the baby's spoon before feeding and occasionally cleans a dropped pacifier with her own mouth. Which explanation best reflects the caries-transmission concept described in the textbook?",
        "option_a": "Lactobacilli permanently colonize the infant's mouth during birth and cannot later be influenced by caregiver habits",
        "option_b": "Mutans streptococci are normally present in a newborn's mouth and become pathogenic only after tooth eruption",
        "option_c": "Cariogenic bacteria, particularly mutans streptococci, can be transferred to the child through saliva from close caregivers",
        "option_d": "Only fermentable carbohydrates, rather than bacteria, can be transmitted between caregiver and infant",
        "correct_option": "C",
    },
    {
        "pk": 4,
        "question": "A 61-year-old patient reports dry mouth since several medications were added to his medical regimen. He chews paraffin for five minutes during a caries-risk assessment and produces 3.5 mL of saliva. The patient has two new cervical lesions, frequently drinks water, and denies regular candy consumption. How should this stimulated salivary flow rate be classified according to Modern Dental Assisting?",
        "option_a": "Normal",
        "option_b": "Low",
        "option_c": "Dry/high-risk range",
        "option_d": "Invalid because the collection period exceeded three minutes",
        "correct_option": "B",
    },
    {
        "pk": 5,
        "question": "A 35-year-old patient has three new carious lesions despite having two teeth restored the previous year. The patient says, 'If you fill all the cavities, shouldn't that solve the problem?' His diet includes frequent sweetened beverages, but he uses fluoridated toothpaste and has normal salivary flow. Which response best reflects the CAMBRA approach described in the textbook?",
        "option_a": "Restoring existing lesions is sufficient provided all visible caries is removed",
        "option_b": "The patient should be classified only by the number of restorations required and then placed on a standard recall interval",
        "option_c": "Risk and protective factors should be assessed, a risk category assigned, and preventive recommendations individualized accordingly",
        "option_d": "Bacterial risk should be ignored once restorative treatment has begun",
        "correct_option": "C",
    },
    {
        "pk": 6,
        "question": "A 23-year-old patient has several new smooth-surface lesions. A salivary bacterial test demonstrates a particularly high lactobacilli count. The patient insists that she 'hardly eats sweets,' but describes frequently consuming crackers, sweetened yogurt, granola bars and flavoured drinks throughout the day. What does the elevated lactobacilli count most strongly support according to the textbook?",
        "option_a": "A high level of calculus formation",
        "option_b": "A high intake of fermentable carbohydrate",
        "option_c": "Advanced periodontal destruction",
        "option_d": "Inadequate systemic fluoride during tooth development",
        "correct_option": "B",
    },
    {
        "pk": 7,
        "question": "A 54-year-old patient has a large posterior restoration that appears clinically intact. The margins are difficult to inspect because of the restoration's location, and an explorer does not reveal an obvious defect. A bitewing image shows a radiolucent area beneath one margin. Which feature of recurrent caries best explains this finding?",
        "option_a": "Recurrent caries usually develops only on exposed root surfaces and cannot be detected clinically",
        "option_b": "It develops in small spaces between a restoration and tooth structure and may require radiographic detection",
        "option_c": "It develops only when plaque is visible on the restoration surface",
        "option_d": "It occurs because restorative material permanently prevents remineralization of adjacent enamel",
        "correct_option": "B",
    },
    {
        "pk": 8,
        "question": "A 46-year-old patient underwent head-and-neck cancer therapy several years ago and now has marked xerostomia. Although he brushes carefully, multiple new lesions have appeared over a short period on several different surfaces. He reports sucking on hard candies to relieve the dryness. Which term best describes the pattern of caries developing rapidly and extensively throughout the mouth?",
        "option_a": "Incipient caries",
        "option_b": "Recurrent caries",
        "option_c": "Rampant caries",
        "option_d": "Arrested caries",
        "correct_option": "C",
    },
    {
        "pk": 9,
        "question": "A high-caries-risk patient has normal salivary flow but frequent exposure to sweetened beverages between meals, multiple recent restorations and poor plaque control. The patient asks why the dental team is discussing diet, fluoride, plaque control and xylitol rather than simply scheduling restorations. Which statement best explains the preventive rationale?",
        "option_a": "Caries reflects a balance between disease-promoting and protective factors, so prevention should shift that balance toward protection",
        "option_b": "Fluoride eliminates all cariogenic bacteria and makes dietary changes unnecessary",
        "option_c": "Restorations eliminate the bacterial cause of caries once margins are intact",
        "option_d": "Diet is relevant only when salivary flow is reduced",
        "correct_option": "A",
    },
    {
        "pk": 10,
        "question": "Parents bring their 3-year-old for the child's first dental examination. The child frequently falls asleep while drinking milk from a bottle and receives juice in a sippy cup throughout the day. The parents brush the child's teeth most evenings but believe primary teeth are 'temporary anyway.' Which recommendation most directly targets an important preventable factor in early childhood caries?",
        "option_a": "Replace milk in the nighttime bottle with fruit juice because juice clears the mouth more rapidly",
        "option_b": "Avoid putting the child to bed with a bottle or sippy cup containing anything other than water",
        "option_c": "Delay brushing until the child can perform it independently",
        "option_d": "Use a slowly dissolving sugar-free candy at bedtime to stimulate saliva",
        "correct_option": "B",
    },
    {
        "pk": 11,
        "question": "A 40-year-old patient reports occasional bleeding when flossing. Examination shows red, slightly edematous gingiva with plaque accumulation, but no recession, attachment loss or radiographic bone loss. The patient is worried because a parent lost teeth from periodontal disease. Which diagnosis most closely fits the tissue changes described?",
        "option_a": "Gingivitis",
        "option_b": "Periodontitis",
        "option_c": "Occlusal trauma",
        "option_d": "Necrotizing periodontal disease",
        "correct_option": "A",
    },
    {
        "pk": 12,
        "question": "A 48-year-old patient has generalized inflammation, several 6-mm probing depths and radiographic interproximal bone loss. Another patient in the next operatory has similarly red gingiva and bleeding during probing but probing depths of 2–3 mm and no attachment or bone loss. Which finding most clearly separates the first patient's disease process from gingivitis?",
        "option_a": "Gingival redness",
        "option_b": "Bleeding during probing",
        "option_c": "Loss of supporting periodontal attachment and alveolar bone",
        "option_d": "Presence of bacterial plaque",
        "correct_option": "C",
    },
    {
        "pk": 13,
        "question": "A patient has heavy mineralized deposits primarily on the lingual surfaces of the mandibular incisors and buccal surfaces of the maxillary molars. The patient brushes once daily and asks why those areas seem to accumulate deposits more rapidly than other surfaces. Which explanation best matches the textbook?",
        "option_a": "These surfaces are adjacent to the openings of major salivary ducts and are common sites for supragingival calculus",
        "option_b": "These areas have the least contact with saliva and therefore retain calcium salts",
        "option_c": "Calculus develops only where gingival bleeding supplies iron pigments",
        "option_d": "These are the only tooth surfaces on which plaque can mineralize",
        "correct_option": "A",
    },
    {
        "pk": 14,
        "question": "During periodontal debridement, dark green-black mineralized deposits are located on root surfaces below the gingival margin. The patient has generalized bleeding and several periodontal pockets. Which feature best explains the darker colour of these deposits?",
        "option_a": "Staining associated with subgingival bleeding",
        "option_b": "Increased fluoride incorporation into the calculus",
        "option_c": "Greater exposure to tobacco smoke than supragingival deposits",
        "option_d": "Absorption of pigments from salivary duct secretions",
        "correct_option": "A",
    },
    {
        "pk": 15,
        "question": "Two patients have similar amounts of plaque and calculus. Patient A does not smoke and has no significant medical history. Patient B smokes daily. Radiographs of Patient B show substantially greater attachment and bone loss. Which interpretation is most consistent with the periodontal risk information in the textbook?",
        "option_a": "Smoking may increase periodontal destruction and can reduce the effectiveness of periodontal treatment",
        "option_b": "Smoking protects the gingiva by reducing visible bleeding, so the radiographic changes are unrelated",
        "option_c": "Smoking primarily increases caries risk but has little effect on periodontal attachment",
        "option_d": "Smoking causes periodontal disease even in the complete absence of disease-causing bacteria",
        "correct_option": "A",
    },
    {
        "pk": 16,
        "question": "A patient with poorly controlled diabetes has deeper pockets and more attachment loss than another patient of similar age whose diabetes is well controlled. Their home-care habits are comparable. Which statement best reflects the relationship described in Modern Dental Assisting?",
        "option_a": "Diabetes has no meaningful effect once plaque levels are similar",
        "option_b": "Diabetes is a significant periodontal risk factor, and poorer metabolic control is associated with more attachment and bone loss",
        "option_c": "Diabetes affects only gingival colour, not periodontal support",
        "option_d": "Periodontal disease occurs only in patients receiving insulin",
        "correct_option": "B",
    },
    {
        "pk": 17,
        "question": "A 16-year-old orthodontic patient has fixed brackets and arch wires. At review, plaque has accumulated around several brackets and the marginal gingiva is red and enlarged. There is no attachment or radiographic bone loss. Which explanation is most appropriate?",
        "option_a": "Orthodontic appliances can retain biofilm and food debris, contributing to gingivitis when home care is inadequate",
        "option_b": "Gingival inflammation is an unavoidable physiologic effect of orthodontic tooth movement",
        "option_c": "The appliances have caused periodontitis because any appliance-related inflammation includes bone loss",
        "option_d": "The inflammation is most likely unrelated to plaque because the brackets prevent plaque from contacting gingiva",
        "correct_option": "A",
    },
    {
        "pk": 18,
        "question": "A patient maintains fairly good daily brushing, but a posterior crown has a pronounced overhanging margin extending subgingivally. Persistent localized inflammation remains around this tooth despite improvement elsewhere. Which interpretation best fits the textbook's discussion of periodontal risk?",
        "option_a": "A local plaque-retentive factor can contribute to progression of periodontal disease",
        "option_b": "Once oral hygiene improves, restorative contours no longer affect periodontal tissues",
        "option_c": "Overhanging restorations are systemic rather than local risk factors",
        "option_d": "The finding indicates that calculus, rather than biofilm, is the sole cause of periodontal disease",
        "correct_option": "A",
    },
    {
        "pk": 19,
        "question": "A patient has completed periodontal therapy and says, 'I brush twice a day, so whatever remains between the teeth probably doesn't matter.' The gingiva is significantly improved, but small areas of plaque remain interproximally. What is the most appropriate preventive goal?",
        "option_a": "Remove plaque thoroughly from tooth and adjacent tissue surfaces at least once daily using methods appropriate to the patient's needs",
        "option_b": "Eliminate all oral bacteria permanently with antimicrobial rinses",
        "option_c": "Brush only surfaces on which visible plaque is present",
        "option_d": "Avoid interproximal cleaning because gingival tissue has recently been treated",
        "correct_option": "A",
    },
    {
        "pk": 20,
        "question": "During oral-hygiene instruction, disclosing solution reveals heavy plaque along the gingival margins and interproximally. The patient becomes embarrassed and says, 'My teeth didn't look dirty before you put that stuff on.' What is the best educational use of the disclosed plaque?",
        "option_a": "Use the visible plaque to demonstrate where biofilm remains and relate those areas to the patient's disease risk",
        "option_b": "Explain that the colour proves calculus is present and must be removed surgically",
        "option_c": "Tell the patient the stain indicates enamel demineralization rather than plaque",
        "option_d": "Avoid discussing it further because disclosing agents are intended only for professional diagnosis",
        "correct_option": "A",
    },
    {
        "pk": 21,
        "question": "A patient is mainly concerned about brown staining on the maxillary anterior teeth. Examination also reveals plaque on posterior lingual surfaces. The assistant immediately begins a detailed lecture about posterior plaque, but the patient loses interest and repeatedly asks about the anterior stain. Which modification most closely follows the textbook's patient-education approach?",
        "option_a": "Continue with the same message because professional priorities should replace the patient's priorities",
        "option_b": "Begin by understanding the patient's motivation, connect it with identified oral-health needs and then customize recommendations",
        "option_c": "Provide every possible home-care recommendation at the first appointment regardless of the patient's concerns",
        "option_d": "Avoid discussing the staining because preventive education should address plaque only",
        "correct_option": "B",
    },
    {
        "pk": 22,
        "question": "A 7-year-old child brushes independently each evening. The parent says the child spends several minutes brushing and therefore probably does not need help. Disclosing solution shows widespread plaque on posterior and lingual surfaces. Which recommendation is most appropriate according to the textbook?",
        "option_a": "Continue independent brushing because time spent brushing is more important than dexterity",
        "option_b": "Have an adult assist or supervise because children younger than about 8 often lack sufficient manual dexterity for thorough cleaning",
        "option_c": "Replace brushing with an antimicrobial rinse until permanent teeth erupt",
        "option_d": "Use dental floss only because flossing requires less dexterity than brushing",
        "correct_option": "B",
    },
    {
        "pk": 23,
        "question": "A 32-year-old patient has healthy gingiva, minimal plaque and an established brushing method that appears effective when demonstrated in the operatory. The assistant prefers another technique and plans to replace the patient's method with the Bass technique solely because the Bass method is frequently recommended. Which approach is more appropriate?",
        "option_a": "Change the technique whenever the patient is not already using Bass",
        "option_b": "Observe effectiveness first and avoid unnecessarily replacing an effective technique in a patient with healthy tissues and good plaque control",
        "option_c": "Switch all adults to powered toothbrushes because manual brushing cannot provide adequate plaque removal",
        "option_d": "Recommend brushing only once weekly if gingiva is healthy",
        "correct_option": "B",
    },
    {
        "pk": 24,
        "question": "A patient with gingival inflammation is being taught a brushing method. The assistant positions the bristles at approximately a 45-degree angle to the tooth surface near the gingival margin and demonstrates a short vibrating back-and-forth motion beginning at the distal aspect of the arch. Which method is being demonstrated?",
        "option_a": "Bass method",
        "option_b": "Fones method",
        "option_c": "Roll method",
        "option_d": "Horizontal scrub method",
        "correct_option": "A",
    },
    {
        "pk": 25,
        "question": "A 66-year-old patient has arthritis affecting both hands and says that grasping a narrow manual toothbrush handle has become difficult. The patient remains motivated and has no cognitive impairment. Which recommendation best reflects the textbook's discussion of toothbrush selection?",
        "option_a": "An automatic toothbrush may be useful because the larger handle can be easier for patients with physical limitations",
        "option_b": "A hard-bristled manual brush is preferred because it requires less hand movement",
        "option_c": "Toothbrushing should be discontinued and replaced entirely by floss",
        "option_d": "Powered brushes should be reserved for children because they are less effective in adults",
        "correct_option": "A",
    },
    {
        "pk": 26,
        "question": "A patient carefully brushes with fluoridated dentifrice but regularly skips flossing because the mouth 'already feels clean' after brushing. The assistant recommends reversing the order and flossing first. What is one textbook rationale for flossing before brushing?",
        "option_a": "Flossing first allows fluoride from the dentifrice to reach cleaned proximal surfaces more readily",
        "option_b": "Flossing first causes plaque to mineralize so it can be removed during brushing",
        "option_c": "Flossing first eliminates the need to clean posterior teeth with the toothbrush",
        "option_d": "Flossing first prevents all gingival bleeding during subsequent brushing",
        "correct_option": "A",
    },
    {
        "pk": 27,
        "question": "A patient insists that unwaxed floss must clean better because 'the wax obviously leaves something behind.' Another patient prefers waxed floss because unwaxed floss shreds against several older restorations. Which recommendation is best supported by the textbook?",
        "option_a": "Recommend unwaxed floss because it removes significantly more plaque",
        "option_b": "Recommend waxed floss because it has a proven antimicrobial effect",
        "option_c": "Encourage the type the patient will use consistently because research shows no meaningful plaque-removal advantage of waxed over unwaxed floss",
        "option_d": "Advise both patients to avoid floss and use only an oral irrigator",
        "correct_option": "C",
    },
    {
        "pk": 28,
        "question": "A patient with a three-unit fixed bridge is cleaning the visible facial and lingual surfaces well but repeatedly develops inflammation under the pontic. Conventional floss cannot be passed vertically through the contact. Which aid is specifically intended to help in this situation?",
        "option_a": "Bridge threader used with dental floss",
        "option_b": "Tongue scraper",
        "option_c": "Rubber cup",
        "option_d": "Disclosing tablet used as an interproximal cleaner",
        "correct_option": "A",
    },
    {
        "pk": 29,
        "question": "A patient with gingival recession has several large open embrasures that retain food. Ordinary floss passes through the spaces without contacting much of the proximal tooth surface. There are no fixed orthodontic appliances. Which home-care aid would be particularly useful for cleansing these wider interdental spaces?",
        "option_a": "Interdental brush or appropriate interdental aid",
        "option_b": "Hard-bristled end-tuft brush used on the occlusal surface only",
        "option_c": "Fluoride tray worn while eating",
        "option_d": "Bridge threader without floss",
        "correct_option": "A",
    },
    {
        "pk": 30,
        "question": "While demonstrating flossing, a patient forces the floss sharply through the contact until it snaps against the papilla, then pulls it straight up without adapting it to either tooth. Which correction is most appropriate?",
        "option_a": "Use a gentle sawing motion through the contact, curve the floss into a C-shape against one tooth and move it along the proximal surface",
        "option_b": "Continue snapping the floss because tissue trauma stimulates keratinization",
        "option_c": "Use only a horizontal motion above the contact point",
        "option_d": "Keep the floss centered between the teeth rather than adapting it to either tooth",
        "correct_option": "A",
    },
    {
        "pk": 31,
        "question": "A 15-year-old patient consumes a large dessert with dinner once each evening. Her sibling eats much smaller amounts of crackers, candy and sweetened snacks repeatedly from after school until bedtime. Both brush twice daily and have similar fluoride exposure. Which dietary pattern presents the greater caries concern according to the textbook?",
        "option_a": "The larger single dessert because total carbohydrate quantity is always the dominant factor",
        "option_b": "The frequent snacking pattern because frequency of cariogenic exposure is especially important",
        "option_c": "Both patterns are equivalent because only sucrose concentration matters",
        "option_d": "Neither pattern matters if the patient brushes twice daily",
        "correct_option": "B",
    },
    {
        "pk": 32,
        "question": "A patient is trying to reduce caries risk and asks which of two snacks is likely to remain cariogenic longer in the mouth: a sweetened beverage swallowed relatively quickly or a sticky caramel that adheres to pits, fissures and proximal surfaces. Which factor makes the caramel more concerning?",
        "option_a": "Retentive foods can remain in the mouth longer and prolong bacterial access to fermentable carbohydrate",
        "option_b": "Liquids cannot contain fermentable carbohydrate",
        "option_c": "Sticky foods produce caries only because they contain fat",
        "option_d": "Retention affects periodontal disease but not caries",
        "correct_option": "A",
    },
    {
        "pk": 33,
        "question": "A university student says she has 'cut out sweets' but snacks on plain crackers throughout the day while studying. Several new smooth-surface lesions are present. She is surprised because the crackers do not taste sweet. Which explanation is most appropriate?",
        "option_a": "Crackers can be cariogenic because refined starches may remain on teeth and be broken down into sugars available to plaque bacteria",
        "option_b": "Only foods containing added sucrose are cariogenic",
        "option_c": "Crackers cause decay only when eaten with dairy products",
        "option_d": "Starches are nonfermentable and therefore unrelated to acid production",
        "correct_option": "A",
    },
    {
        "pk": 34,
        "question": "A patient agrees to complete a food diary for nutritional counselling. She records 'breakfast, sandwich, dinner' for three days but leaves out quantities, preparation methods, beverages, snacks and times. Which additional information is most important for a useful dietary analysis as described in the textbook?",
        "option_a": "Every food and beverage consumed, the amount, how it was prepared and when it was eaten",
        "option_b": "Only the total number of calories consumed each day",
        "option_c": "Only foods that contain visible added sugar",
        "option_d": "Only meals eaten outside the home",
        "correct_option": "A",
    },
    {
        "pk": 35,
        "question": "During review of the diary, the assistant notices frequent sugary snacks and several nutritionally weak food choices. The patient appears embarrassed and says, 'I know this looks terrible.' Which counselling approach best follows the textbook?",
        "option_a": "Clearly criticize the poorest choices so the patient understands the seriousness",
        "option_b": "Suggest realistic modifications positively and avoid presenting the analysis in a way that makes the patient uncomfortable",
        "option_c": "Avoid discussing any problems unless the patient specifically asks",
        "option_d": "Replace the patient's entire diet with a fixed menu created by the dental office",
        "correct_option": "B",
    },
    {
        "pk": 36,
        "question": "A patient asks why eating a small sugary snack every hour may be more damaging than eating the same total amount of sugar with a meal. The patient's salivary flow is normal. Which explanation best reflects the textbook's preventive emphasis?",
        "option_a": "Repeated exposures create repeated opportunities for plaque bacteria to metabolize fermentable carbohydrate and challenge the teeth with acid",
        "option_b": "Sugar eaten with meals cannot be fermented by plaque bacteria",
        "option_c": "Total amount has no role at all in caries development",
        "option_d": "Saliva neutralizes acid instantly, making frequency irrelevant",
        "correct_option": "A",
    },
    {
        "pk": 37,
        "question": "A xerostomic patient habitually sucks slowly dissolving sugar-containing lozenges throughout the day for comfort. She asks whether a different strategy could help stimulate saliva without creating the same cariogenic exposure. Which recommendation best fits the textbook's caries-intervention discussion?",
        "option_a": "Sugar-free gum, particularly a product containing xylitol",
        "option_b": "Sticky caramel because chewing increases salivary flow",
        "option_c": "Sweetened juice in small sips",
        "option_d": "Sucrose lozenges used only between meals",
        "correct_option": "A",
    },
    {
        "pk": 38,
        "question": "A patient finishes a three-day food diary and the dental assistant is preparing for counselling. The diary includes frequent snack exposures, several sticky refined-carbohydrate foods and very few foods that stimulate mastication. The patient's chief complaint, however, is 'weak enamel.' What should the dental team do first with the completed diary?",
        "option_a": "Review and organize the recorded intake with the patient, identify cariogenic patterns and compare the diet with recommended intake before setting changes",
        "option_b": "Prescribe fluoride without discussing dietary findings",
        "option_c": "Discard the diary because only salivary bacterial testing determines dietary risk",
        "option_d": "Calculate only total sugar grams and ignore timing and food consistency",
        "correct_option": "A",
    },
    {
        "pk": 39,
        "question": "A 50-year-old patient has multiple ceramic crowns and several large composite restorations. The dentist prescribes an in-office topical fluoride treatment because of high caries risk. The assistant is deciding between acidulated phosphate fluoride and a neutral sodium fluoride product. Which choice is most appropriate based on the textbook?",
        "option_a": "Acidulated phosphate fluoride because its acidity protects ceramics",
        "option_b": "Neutral sodium fluoride because APF should be avoided around ceramic and composite restorations",
        "option_c": "Either product because restorations do not influence fluoride selection",
        "option_d": "Stannous fluoride because it is the only professional fluoride compatible with restorations",
        "correct_option": "B",
    },
    {
        "pk": 40,
        "question": "Before tray fluoride application, an assistant notices generalized plaque but no calculus. She suggests polishing the entire dentition first so fluoride can reach the enamel. The hygienist says polishing is unnecessary. Which statement best explains the hygienist's response?",
        "option_a": "Plaque does not prevent fluoride uptake in the way calculus does",
        "option_b": "Fluoride cannot diffuse through the acquired pellicle",
        "option_c": "Plaque increases fluoride toxicity and therefore must remain undisturbed",
        "option_d": "Only stains, not calculus, interfere with fluoride reaching enamel",
        "correct_option": "A",
    },
    {
        "pk": 41,
        "question": "A patient is receiving fluoride gel in trays. The assistant seats the patient completely supine, fills the trays generously 'to make sure every surface gets enough,' and plans to leave the room while the timer runs. Which change is most important for safe technique?",
        "option_a": "Seat the patient upright, use only the appropriate minimal amount, provide suction and monitor the patient",
        "option_b": "Keep the patient supine but eliminate suction",
        "option_c": "Increase the amount of fluoride and shorten the treatment time",
        "option_d": "Ask the patient to swallow periodically to clear excess saliva",
        "correct_option": "A",
    },
    {
        "pk": 42,
        "question": "Immediately after professional fluoride gel application, a patient asks whether she can rinse thoroughly and have a coffee before returning to work. Which instruction best matches the textbook procedure?",
        "option_a": "Rinse immediately but avoid hot beverages for four hours",
        "option_b": "Do not rinse, eat, drink or brush for at least 30 minutes",
        "option_c": "Brush immediately to spread the fluoride over additional surfaces",
        "option_d": "Drink water immediately because dilution increases fluoride uptake",
        "correct_option": "B",
    },
    {
        "pk": 43,
        "question": "A young patient has difficulty tolerating fluoride trays because of gagging. The dentist instead prescribes fluoride varnish. During setup, the assistant is worried because perfect isolation cannot be maintained and small amounts of saliva contact the teeth. Which statement best distinguishes varnish from the tray gel procedure described in the textbook?",
        "option_a": "Fluoride varnish is not moisture sensitive and may be applied in the presence of saliva",
        "option_b": "Varnish must be kept completely dry or it will fail to polymerize",
        "option_c": "Saliva converts varnish into APF and damages ceramic restorations",
        "option_d": "Varnish cannot be used when isolation is difficult",
        "correct_option": "A",
    },
    {
        "pk": 44,
        "question": "After fluoride varnish placement, an adult patient plans to have a hot dinner, brush thoroughly and floss immediately because she dislikes the coating. Which instruction is most appropriate?",
        "option_a": "Remove the varnish immediately because the procedure is complete once the material is placed",
        "option_b": "Avoid hard foods, hot or alcoholic beverages, brushing and flossing for the recommended several hours to prolong contact",
        "option_c": "Brush immediately but avoid flossing for 30 minutes",
        "option_d": "Rinse repeatedly with hot water to distribute the varnish",
        "correct_option": "B",
    },
    {
        "pk": 45,
        "question": "A 10-year-old patient lives in a home supplied by nonfluoridated well water but attends school in an area with fluoridated municipal water. The family also frequently uses bottled beverages and processed foods. The parent asks whether a fluoride supplement should automatically be prescribed. Which consideration is most appropriate?",
        "option_a": "Prescribe supplementation whenever the home water source is nonfluoridated",
        "option_b": "Evaluate the child's total fluoride exposure from drinking water and other sources before deciding on supplementation",
        "option_c": "Avoid all fluoride supplements because topical fluoride is the only useful form after infancy",
        "option_d": "Base supplementation only on the number of permanent teeth erupted",
        "correct_option": "B",
    },
    {
        "pk": 46,
        "question": "An 8-year-old patient has a fully erupted permanent first molar with deep, narrow pits and fissures. The opposite first molar required an occlusal restoration the previous year. Bitewings show no proximal caries on the tooth being considered, and the child is cooperative. Which conclusion is most appropriate?",
        "option_a": "The tooth is a good candidate for a pit-and-fissure sealant",
        "option_b": "The previous restoration on the opposite side is a contraindication",
        "option_c": "Sealant should be delayed until an overt cavitated lesion develops",
        "option_d": "Permanent molars should not be sealed after complete eruption",
        "correct_option": "A",
    },
    {
        "pk": 47,
        "question": "A 7-year-old patient's mandibular first molar has begun erupting but part of the occlusal surface remains covered by gingival tissue. Deep pits will probably be present once eruption is complete. The child is cooperative and has a high caries-risk history. What is the primary reason to postpone sealant placement on this tooth?",
        "option_a": "A high-caries-risk child should never receive sealants",
        "option_b": "The tooth is insufficiently erupted to expose and isolate the entire occlusal surface reliably",
        "option_c": "Recently erupted permanent teeth have little risk for decay",
        "option_d": "Gingival tissue chemically prevents acid etching of enamel",
        "correct_option": "B",
    },
    {
        "pk": 48,
        "question": "During placement of a light-cured sealant, a permanent molar has been cleaned, isolated, etched and rinsed. The dried enamel initially appears frosty. While the assistant changes a cotton roll, saliva briefly contacts the etched occlusal surface. What should be done before sealant application?",
        "option_a": "Dry the tooth and apply sealant without further treatment",
        "option_b": "Re-etch the contaminated enamel before proceeding",
        "option_c": "Apply more sealant to compensate for the contamination",
        "option_d": "Cure the enamel first and then place sealant",
        "correct_option": "B",
    },
    {
        "pk": 49,
        "question": "Immediately after curing a posterior sealant, the patient says the tooth feels high when biting. Articulating paper reveals a heavy mark over the sealed groove. The operator had applied a relatively thick layer of material. Which explanation is most likely?",
        "option_a": "Excess sealant material has created an occlusal interference",
        "option_b": "Inadequate etching has shortened the tooth",
        "option_c": "Moisture contamination has increased the vertical dimension of the enamel",
        "option_d": "The sealant has blocked the proximal contact rather than the occlusal surface",
        "correct_option": "A",
    },
    {
        "pk": 50,
        "question": "At a recall visit, a sealant is still present on most of a molar, but staining is visible along one peripheral area and the explorer suggests a small marginal defect. The patient has no symptoms and assumes the sealant is still protective because most of it remains. Which action best reflects the textbook's concern?",
        "option_a": "Leave it indefinitely because any remaining sealant protects the entire fissure system",
        "option_b": "Evaluate the defect for leakage and repair or replace a lost/leaking sealant as indicated",
        "option_c": "Remove every intact sealant at each recall and place a new one",
        "option_d": "Ignore marginal staining unless the patient develops spontaneous pain",
        "correct_option": "B",
    },
]


class Command(BaseCommand):
    help = "Loads the preventive procedure questions into the database."

    def handle(self, *args, **kwargs):
        created_count = 0
        updated_count = 0

        for q in QUESTIONS_DATA:
            obj, created = Question.objects.update_or_create(
                pk=q["pk"],
                defaults={
                    "question": q["question"],
                    "option_a": q["option_a"],
                    "option_b": q["option_b"],
                    "option_c": q["option_c"],
                    "option_d": q["option_d"],
                    "correct_option": q["correct_option"],
                },
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully processed questions! Created: {created_count}, Updated: {updated_count}"
            )
        )